-- This migration was generated from an earlier, abandoned UserMemory shape.
-- The current schema creates UserMemory in add_user_memory with the correct
-- primary key and updatedAt column, so this historical migration is kept as a
-- no-op to preserve migration ordering for fresh databases.
